version: "3.8"
services:
  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: naamko_sales_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: location_reports_secure_password_2025
      POSTGRES_DB: location_reports
    ports:
      - "5432:5432"
    networks:
      app-network:
        aliases:
          - postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Express API Service
  express-api:
    build:
      context: ./express-api
      dockerfile: Dockerfile
    container_name: naamko_sales_express_api
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: location_reports_secure_password_2025
      DB_NAME: location_reports
      DATABASE_URL: "postgresql://postgres:location_reports_secure_password_2025@postgres:5432/location_reports"
      JWT_SECRET: your_super_secure_jwt_secret_key
      NODE_ENV: development
      BASE_PATH: "/api"
      HMAC_SECRET: your_super_secret_hmac_key_make_it_very_long_and_random_123456789
      APP_ID: naamko-location-app
    networks:
      app-network:
        aliases:
          - express-api
    volumes:
      - uploads_data:/app/uploads

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: naamko_sales_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - uploads_data:/app/uploads:ro
    depends_on:
      - express-api
    networks:
      app-network:
        aliases:
          - nginx

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
